// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdvyrphneojlwbzefokj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkdnlycGhuZW9qbHdiemVmb2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzOTUzNTMsImV4cCI6MjA2ODk3MTM1M30.3HLrb_xVdNr0c8VLDDxGfgVPf7G89wyCQatGmdgaCQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});